### ISSUE TITLE
Cannot build binaries on Ubuntu

### ISSUE THREAD

**Issue by meichengg** [sysdream/chashell#10]
Hi, i'm having multiple issues with installing dependencies and building binaries. Can you please troubleshoot me? Thanks.

![image](https://user-images.githubusercontent.com/25204246/114686709-3ef8f100-9d3d-11eb-825d-cc5bb918e79d.png)

**Comment by Ach13v3-M0n7** [comment]
I had a similar issue on an Ubuntu 18.04 build. I fixed it by ensuring dep and gox were installed before running the build command:
`sudo apt install go-dep`
`go get github.com/mitchellh/gox`

With these manually installed, I was able to build both server and client.
