### ISSUE TITLE
Server SIGSEGV

### ISSUE THREAD

**Issue by T-S-A** [sysdream/chashell#2]
I get the following when running the chashell_windows_386.exe or chashell_windows_amd64.exe client. If I run the linux or Mac OS clients, no server segmentation violation -- it all seems to work fine.

chashell >>> New session : 5ca22ca7f044be1438d8cc0a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x46a0b6]

goroutine 42 [running]:
bytes.(*Buffer).Write(0x0, 0xc0000b0cc0, 0x24, 0x40, 0xb08b20, 0x0, 0x18)
        /usr/local/opt/go/libexec/src/bytes/buffer.go:172 +0x26
main.parseQuery(0xc0000b59e0)
        /Users/user/go/src/chashell/cmd/server/chaserv.go:149 +0xc6b
main.handleDNSRequest(0x862a40, 0xc0000bcd80, 0xc0000b5950)
        /Users/user/go/src/chashell/cmd/server/chaserv.go:175 +0xac
chashell/vendor/github.com/miekg/dns.HandlerFunc.ServeDNS(0x7fc2a8, 0x862a40, 0xc0000bcd80, 0xc0000b5950)
        /Users/user/go/src/chashell/vendor/github.com/miekg/dns/server.go:52 +0x44
chashell/vendor/github.com/miekg/dns.(*ServeMux).ServeDNS(0xc00000c2e0, 0x862a40, 0xc0000bcd80, 0xc0000b5950)
        /Users/user/go/src/chashell/vendor/github.com/miekg/dns/serve_mux.go:128 +0x5d
chashell/vendor/github.com/miekg/dns.(*Server).serveDNS(0xc0000c2000, 0xc0000bcd80)
        /Users/user/go/src/chashell/vendor/github.com/miekg/dns/server.go:687 +0x298
chashell/vendor/github.com/miekg/dns.(*Server).serve(0xc0000c2000, 0xc0000bcd80)
        /Users/user/go/src/chashell/vendor/github.com/miekg/dns/server.go:572 +0x2bc
chashell/vendor/github.com/miekg/dns.(*Server).worker(0xc0000c2000, 0xc0000bc100)
        /Users/user/go/src/chashell/vendor/github.com/miekg/dns/server.go:269 +0x1bf
created by chashell/vendor/github.com/miekg/dns.(*Server).spawnWorker
        /Users/user/go/src/chashell/vendor/github.com/miekg/dns/server.go:284 +0x83

**Comment by nicocha30** [comment]
Hi @T-S-A , this issue should now be solved! Thanks for the report.

**Comment by T-S-A** [comment]
Thanks, I'll check that change out!
