### ISSUE TITLE
Undefined: protocol.Message_Infopacket

### ISSUE THREAD

**Issue by T-S-A** [sysdream/chashell#5]
I've tried building on multiple machines. Can't because protocol.Message_Infopacket is undefined.

***************************************

make build dep
dep ensure && \
go build -ldflags "-X main.targetDomain=c.xxxxxxxxxxxxxxxxxxx-X main.encryptionKey=xxxxxxxxxxxxxxxxxxx -s -w" -gcflags "all=-trimpath=OPATH" -tags release -o release/chashell ./cmd/shell && \
go build -ldflags "-X main.targetDomain=c.xxxxxxxxxxxxxxxxxxx-X main.encryptionKey=xxxxxxxxxxxxxxxxxxx -s -w" -gcflags "all=-trimpath=OPATH" -tags release -o release/chaserv ./cmd/server
# chashell/lib/transport
../../../chashell/lib/transport/polling.go:80:12: undefined: protocol.Message_Infopacket
make: *** [Makefile:27: build] Error 2

**Comment by nicocha30** [comment]
Hi @T-S-A , can you test with the latest version ? 

Thanks,

Nicolas.

**Comment by T-S-A** [comment]
Works! Thx.
