### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [sysdream/chashell#9]
I think it is mainly a problem of my missing go knowledge, but im getting the following error for compiling on debian linux/amd64:

`--> linux/amd64 error: exit status 1
Stderr: chashell.go:4:2: cannot find package "chashell/lib/transport" in any of:
        /usr/lib/go-1.11/src/chashell/lib/transport (from $GOROOT)
        /root/.go/src/chashell/lib/transport (from $GOPATH)
`
dep ensure ran successfully. What am i missing?

**Comment by kosherpork** [comment]
This should fix it:

```
cd `go env GOPATH`/src
git clone https://github.com/sysdream/chashell
cd chashell
make dep
make build-all
```

**Comment by S3cur3Th1sSh1t** [comment]
Confirmed thanks!
